In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("Train_Data.csv")

In [3]:
df.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86845 entries, 0 to 86844
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   duration                86845 non-null  int64  
 1   protocoltype            86845 non-null  object 
 2   service                 86845 non-null  object 
 3   flag                    86845 non-null  object 
 4   srcbytes                86845 non-null  int64  
 5   dstbytes                86845 non-null  int64  
 6   land                    86845 non-null  int64  
 7   wrongfragment           86845 non-null  int64  
 8   urgent                  86845 non-null  int64  
 9   hot                     86845 non-null  int64  
 10  numfailedlogins         86845 non-null  int64  
 11  loggedin                86845 non-null  int64  
 12  numcompromised          86845 non-null  int64  
 13  rootshell               86845 non-null  int64  
 14  suattempted             86845 non-null

In [5]:
x_train = df.drop("attack", axis = 1)
y_train = np.array(list(df.iloc[:,-1]))

In [6]:
x_train.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...               15                0.06   
1              0       0    0  ...              116                0.45   
2              0       0    0  ...              255                1.00   
3              0       0    0  ...              255                1.00   
4              0       0    0  ...                3                0.01   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.06                    0.00                    0.00   
1                0.04                    0.00                    0.00   
2                0.00                    0.02                    0.03   
3                0.00                    0.00                    0.00   
4                0.08                    0.00                    0.00   

   dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
0               0.00                   0.0               1.00   
1               0.11                   0.0               0.02   
2               0.00                   0.0               0.00   
3               0.00                   0.0               0.00   
4               0.00                   0.0               1.00   

   dsthostsrvrerrorrate  lastflag  
0                   1.0        21  
1                   0.0        18  
2                   0.0        21  
3                   0.0        21  
4                   1.0        19  

[5 rows x 42 columns]

In [7]:
print("x_train.head(): \n\n {} \n" .format(x_train.head()))
print("x_train.shape: {} \n" .format(x_train.shape))

x_train.head(): 

    duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...               15                0.06   
1              0       0    0  ...              116                0.45   
2              0       0    0  ...              255                1.00   
3              0       0    0  ...              255                1.00   
4              0       0    0  ...                3                0.01   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.06   

In [8]:
y_train

array([1, 0, 0, ..., 0, 0, 0])

In [9]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [1 0 0 ... 0 0 0] 

y_train.shape: (86845,) 



In [10]:
x_test = pd.read_csv("Test_Data.csv")

In [11]:
x_test.head()

duration protocoltype  service flag  srcbytes  dstbytes  land  \
0         0          tcp      mtp  REJ         0         0     0   
1         0          tcp     http   SF       199      1721     0   
2         0          tcp  discard   S0         0         0     0   
3         0          tcp   telnet   S0         0         0     0   
4         0          tcp     exec   S0         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...                7                0.03   
1              0       0    0  ...              255                1.00   
2              0       0    0  ...               14                0.05   
3              0       0    0  ...                2                0.01   
4              0       0    0  ...               16                0.06   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.08                     0.0                     0.0   
1                0.00                     0.0                     0.0   
2                0.09                     0.0                     0.0   
3                0.09                     0.0                     0.0   
4                0.06                     0.0                     0.0   

   dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
0                0.0                   0.0                1.0   
1                0.0                   0.0                0.0   
2                1.0                   1.0                0.0   
3                1.0                   1.0                0.0   
4                1.0                   1.0                0.0   

   dsthostsrvrerrorrate  lastflag  
0                   1.0        20  
1                   0.0        21  
2                   0.0        18  
3                   0.0        18  
4                   0.0        20  

[5 rows x 42 columns]

In [12]:
print("x_test.head(): \n\n {} \n" .format(x_test.head()))
print("x_test.shape: {}" .format(x_test.shape))

x_test.head(): 

    duration protocoltype  service flag  srcbytes  dstbytes  land  \
0         0          tcp      mtp  REJ         0         0     0   
1         0          tcp     http   SF       199      1721     0   
2         0          tcp  discard   S0         0         0     0   
3         0          tcp   telnet   S0         0         0     0   
4         0          tcp     exec   S0         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...                7                0.03   
1              0       0    0  ...              255                1.00   
2              0       0    0  ...               14                0.05   
3              0       0    0  ...                2                0.01   
4              0       0    0  ...               16                0.06   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.08                     0.0    

**Checking Missing data, Duplicates values, Datatypes, No of unique values in each column and Statistics of Dataset**

In [13]:
df.isnull().sum()

duration                  0
protocoltype              0
service                   0
flag                      0
srcbytes                  0
dstbytes                  0
land                      0
wrongfragment             0
urgent                    0
hot                       0
numfailedlogins           0
loggedin                  0
numcompromised            0
rootshell                 0
suattempted               0
numroot                   0
numfilecreations          0
numshells                 0
numaccessfiles            0
numoutboundcmds           0
ishostlogin               0
isguestlogin              0
count                     0
srvcount                  0
serrorrate                0
srvserrorrate             0
rerrorrate                0
srvrerrorrate             0
samesrvrate               0
diffsrvrate               0
srvdiffhostrate           0
dsthostcount              0
dsthostsrvcount           0
dsthostsamesrvrate        0
dsthostdiffsrvrate        0
dsthostsamesrcportra

*Note: There are no missing values*

In [14]:
df.duplicated()

0        False
1        False
2        False
3        False
4        False
         ...  
86840    False
86841    False
86842    False
86843    False
86844    False
Length: 86845, dtype: bool

In [15]:
df[df.duplicated() == True]

Empty DataFrame
Columns: [duration, protocoltype, service, flag, srcbytes, dstbytes, land, wrongfragment, urgent, hot, numfailedlogins, loggedin, numcompromised, rootshell, suattempted, numroot, numfilecreations, numshells, numaccessfiles, numoutboundcmds, ishostlogin, isguestlogin, count, srvcount, serrorrate, srvserrorrate, rerrorrate, srvrerrorrate, samesrvrate, diffsrvrate, srvdiffhostrate, dsthostcount, dsthostsrvcount, dsthostsamesrvrate, dsthostdiffsrvrate, dsthostsamesrcportrate, dsthostsrvdiffhostrate, dsthostserrorrate, dsthostsrvserrorrate, dsthostrerrorrate, dsthostsrvrerrorrate, lastflag, attack]
Index: []

[0 rows x 43 columns]

*Note: There are no duplicate values in the given dataset*

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 86845 entries, 0 to 86844
Data columns (total 43 columns):
 #   Column                  Non-Null Count  Dtype  
---  ------                  --------------  -----  
 0   duration                86845 non-null  int64  
 1   protocoltype            86845 non-null  object 
 2   service                 86845 non-null  object 
 3   flag                    86845 non-null  object 
 4   srcbytes                86845 non-null  int64  
 5   dstbytes                86845 non-null  int64  
 6   land                    86845 non-null  int64  
 7   wrongfragment           86845 non-null  int64  
 8   urgent                  86845 non-null  int64  
 9   hot                     86845 non-null  int64  
 10  numfailedlogins         86845 non-null  int64  
 11  loggedin                86845 non-null  int64  
 12  numcompromised          86845 non-null  int64  
 13  rootshell               86845 non-null  int64  
 14  suattempted             86845 non-null

In [17]:
numerical_features = []
categorical_features = []

for feature in x_train.columns:
    if ((x_train[feature].nunique() <= 10) or x_train[feature].dtype == "object"):
        categorical_features.append(feature)
    else:
        numerical_features.append(feature)

In [18]:
print("Numerical Features: {}" .format(numerical_features))
print("No. of Numerical Features: {}" .format(len(numerical_features)))

Numerical Features: ['duration', 'srcbytes', 'dstbytes', 'hot', 'numcompromised', 'numroot', 'numfilecreations', 'count', 'srvcount', 'serrorrate', 'srvserrorrate', 'rerrorrate', 'srvrerrorrate', 'samesrvrate', 'diffsrvrate', 'srvdiffhostrate', 'dsthostcount', 'dsthostsrvcount', 'dsthostsamesrvrate', 'dsthostdiffsrvrate', 'dsthostsamesrcportrate', 'dsthostsrvdiffhostrate', 'dsthostserrorrate', 'dsthostsrvserrorrate', 'dsthostrerrorrate', 'dsthostsrvrerrorrate', 'lastflag']
No. of Numerical Features: 27


In [19]:
print("Categorical Features: {}" .format(categorical_features))
print("No. of Categorical Features: {}" .format(len(categorical_features)))

Categorical Features: ['protocoltype', 'service', 'flag', 'land', 'wrongfragment', 'urgent', 'numfailedlogins', 'loggedin', 'rootshell', 'suattempted', 'numshells', 'numaccessfiles', 'numoutboundcmds', 'ishostlogin', 'isguestlogin']
No. of Categorical Features: 15


In [20]:
encoded_category = []
non_encoded_category = []

for feature in categorical_features:
    if (x_train[feature].dtype == "object"):
        non_encoded_category.append(feature)
    else:
        encoded_category.append(feature)

In [21]:
print("Encoded Catgeories: {}" .format(encoded_category))
print("No. of Encoded Categories: {}" .format(len(encoded_category)))

Encoded Catgeories: ['land', 'wrongfragment', 'urgent', 'numfailedlogins', 'loggedin', 'rootshell', 'suattempted', 'numshells', 'numaccessfiles', 'numoutboundcmds', 'ishostlogin', 'isguestlogin']
No. of Encoded Categories: 12


In [22]:
print("Non-Encoded Catgeories: {}" .format(non_encoded_category))
print("No. of Non-Encoded Categories: {}" .format(len(non_encoded_category)))

Non-Encoded Catgeories: ['protocoltype', 'service', 'flag']
No. of Non-Encoded Categories: 3


In [23]:
df["attack"].unique()

array([1, 0], dtype=int64)

In [24]:
df["attack"].value_counts()

attack
0    53847
1    32998
Name: count, dtype: int64

In [25]:
df["attack"].nunique()

2

In [26]:
list_unique = []
list_columns = list(df.columns)
for feature in df.columns:
    unique_values = df[feature].unique()
    list_unique.append(unique_values)
    print("feature: {}" .format(feature))
    print("unique values: {}" .format(df[feature].unique()))
    print("no. of unqiue values: {}" .format(df[feature].nunique()))
    print("value counts: {} \n\n " .format(df[feature].value_counts()))

feature: duration
unique values: [    0     3  7930 ...  3355 20771 11343]
no. of unqiue values: 1594
value counts: duration
0        80485
1         1330
2          556
3          375
5          227
         ...  
11204        1
1017         1
1839         1
820          1
11343        1
Name: count, Length: 1594, dtype: int64 

 
feature: protocoltype
unique values: ['tcp' 'udp' 'icmp']
no. of unqiue values: 3
value counts: protocoltype
tcp     75876
udp      9929
icmp     1040
Name: count, dtype: int64 

 
feature: service
unique values: ['netbios_dgm' 'smtp' 'http' 'uucp_path' 'private' 'csnet_ns' 'hostnames'
 'IRC' 'courier' 'ssh' 'Z39_50' 'other' 'ftp_data' 'efs' 'exec' 'telnet'
 'time' 'domain_u' 'auth' 'iso_tsap' 'http_443' 'nnsp' 'gopher' 'vmnet'
 'netstat' 'whois' 'netbios_ns' 'nntp' 'daytime' 'mtp' 'discard' 'echo'
 'netbios_ssn' 'link' 'pop_3' 'ctf' 'ldap' 'uucp' 'ecr_i' 'finger'
 'systat' 'klogin' 'ftp' 'sunrpc' 'sql_net' 'name' 'kshell' 'domain'
 'imap4' 'urp_i' 'login' '

In [27]:
for feature in non_encoded_category:
    print("feature: {}" .format(feature))
    print("unique values: {}" .format(df[feature].unique()))
    print("no. of unqiue values: {}" .format(df[feature].nunique()))
    print("value counts: {} \n\n " .format(df[feature].value_counts()))

feature: protocoltype
unique values: ['tcp' 'udp' 'icmp']
no. of unqiue values: 3
value counts: protocoltype
tcp     75876
udp      9929
icmp     1040
Name: count, dtype: int64 

 
feature: service
unique values: ['netbios_dgm' 'smtp' 'http' 'uucp_path' 'private' 'csnet_ns' 'hostnames'
 'IRC' 'courier' 'ssh' 'Z39_50' 'other' 'ftp_data' 'efs' 'exec' 'telnet'
 'time' 'domain_u' 'auth' 'iso_tsap' 'http_443' 'nnsp' 'gopher' 'vmnet'
 'netstat' 'whois' 'netbios_ns' 'nntp' 'daytime' 'mtp' 'discard' 'echo'
 'netbios_ssn' 'link' 'pop_3' 'ctf' 'ldap' 'uucp' 'ecr_i' 'finger'
 'systat' 'klogin' 'ftp' 'sunrpc' 'sql_net' 'name' 'kshell' 'domain'
 'imap4' 'urp_i' 'login' 'supdup' 'eco_i' 'rje' 'ntp_u' 'bgp' 'pop_2'
 'printer' 'X11' 'tim_i' 'shell' 'remote_job' 'urh_i' 'tftp_u' 'red_i']
no. of unqiue values: 65
value counts: service
http        31505
private     12859
domain_u     7196
smtp         5806
ftp_data     4929
            ...  
printer        46
urh_i           9
red_i           6
tim_i    

In [28]:
x_train.describe()

duration      srcbytes      dstbytes          land  wrongfragment  \
count  86845.000000  8.684500e+04  8.684500e+04  86845.000000        86845.0   
mean     104.166872  8.455707e+03  2.732095e+03      0.000046            0.0   
std     1038.273538  3.582141e+05  5.543041e+04      0.006787            0.0   
min        0.000000  0.000000e+00  0.000000e+00      0.000000            0.0   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000            0.0   
50%        0.000000  4.600000e+01  4.400000e+01      0.000000            0.0   
75%        0.000000  2.720000e+02  7.680000e+02      0.000000            0.0   
max    40504.000000  8.958152e+07  7.028652e+06      1.000000            0.0   

             urgent           hot  numfailedlogins      loggedin  \
count  86845.000000  86845.000000     86845.000000  86845.000000   
mean       0.000035      0.144971         0.000771      0.441142   
std        0.007588      1.837958         0.037009      0.496527   
min        0.000000      0.000000         0.000000      0.000000   
25%        0.000000      0.000000         0.000000      0.000000   
50%        0.000000      0.000000         0.000000      0.000000   
75%        0.000000      0.000000         0.000000      1.000000   
max        2.000000     77.000000         4.000000      1.000000   

       numcompromised  ...  dsthostsrvcount  dsthostsamesrvrate  \
count    86845.000000  ...     86845.000000        86845.000000   
mean         0.320583  ...       123.338269            0.526457   
std         27.993474  ...       112.704010            0.447353   
min          0.000000  ...         0.000000            0.000000   
25%          0.000000  ...        12.000000            0.050000   
50%          0.000000  ...        77.000000            0.550000   
75%          0.000000  ...       255.000000            1.000000   
max       7479.000000  ...       255.000000            1.000000   

       dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
count        86845.000000            86845.000000            86845.000000   
mean             0.050186                0.075810                0.016246   
std              0.103323                0.208388                0.055271   
min              0.000000                0.000000                0.000000   
25%              0.000000                0.000000                0.000000   
50%              0.030000                0.000000                0.000000   
75%              0.070000                0.020000                0.010000   
max              1.000000                1.000000                1.000000   

       dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
count       86845.000000          86845.000000       86845.000000   
mean            0.324666              0.318934           0.092391   
std             0.464291              0.463506           0.282768   
min             0.000000              0.000000           0.000000   
25%             0.000000              0.000000           0.000000   
50%             0.000000              0.000000           0.000000   
75%             1.000000              1.000000           0.000000   
max             1.000000              1.000000           1.000000   

       dsthostsrvrerrorrate      lastflag  
count          86845.000000  86845.000000  
mean               0.091045     20.060522  
std                0.281452      1.421425  
min                0.000000      1.000000  
25%                0.000000     19.000000  
50%                0.000000     21.000000  
75%                0.000000     21.000000  
max                1.000000     21.000000  

[8 rows x 39 columns]

In [29]:
x_test.describe()

duration      srcbytes      dstbytes          land  wrongfragment  \
count  21712.000000  2.171200e+04  2.171200e+04  21712.000000        21712.0   
mean     106.245901  6.913654e+03  2.501202e+03      0.000138            0.0   
std      999.667098  1.708063e+05  3.200111e+04      0.011754            0.0   
min        0.000000  0.000000e+00  0.000000e+00      0.000000            0.0   
25%        0.000000  0.000000e+00  0.000000e+00      0.000000            0.0   
50%        0.000000  4.600000e+01  4.500000e+01      0.000000            0.0   
75%        0.000000  2.730000e+02  7.662500e+02      0.000000            0.0   
max    29053.000000  1.881556e+07  2.072416e+06      1.000000            0.0   

             urgent           hot  numfailedlogins      loggedin  \
count  21712.000000  21712.000000     21712.000000  21712.000000   
mean       0.000322      0.135547         0.001197      0.439711   
std        0.026283      1.754313         0.046014      0.496363   
min        0.000000      0.000000         0.000000      0.000000   
25%        0.000000      0.000000         0.000000      0.000000   
50%        0.000000      0.000000         0.000000      0.000000   
75%        0.000000      0.000000         0.000000      1.000000   
max        3.000000     30.000000         4.000000      1.000000   

       numcompromised  ...  dsthostsrvcount  dsthostsamesrvrate  \
count    21712.000000  ...     21712.000000        21712.000000   
mean         0.290485  ...       123.794123            0.529036   
std         13.828341  ...       112.653798            0.446966   
min          0.000000  ...         0.000000            0.000000   
25%          0.000000  ...        12.000000            0.050000   
50%          0.000000  ...        79.000000            0.560000   
75%          0.000000  ...       255.000000            1.000000   
max       1043.000000  ...       255.000000            1.000000   

       dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
count        21712.000000            21712.000000            21712.000000   
mean             0.049770                0.077574                0.017072   
std              0.101695                0.210789                0.059514   
min              0.000000                0.000000                0.000000   
25%              0.000000                0.000000                0.000000   
50%              0.020000                0.000000                0.000000   
75%              0.070000                0.020000                0.020000   
max              1.000000                1.000000                1.000000   

       dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
count       21712.000000          21712.000000       21712.000000   
mean            0.322726              0.317352           0.092314   
std             0.463536              0.463013           0.282506   
min             0.000000              0.000000           0.000000   
25%             0.000000              0.000000           0.000000   
50%             0.000000              0.000000           0.000000   
75%             1.000000              1.000000           0.000000   
max             1.000000              1.000000           1.000000   

       dsthostsrvrerrorrate      lastflag  
count          21712.000000  21712.000000  
mean               0.091670     20.061395  
std                0.282055      1.420926  
min                0.000000      1.000000  
25%                0.000000     19.000000  
50%                0.000000     21.000000  
75%                0.000000     21.000000  
max                1.000000     21.000000  

[8 rows x 39 columns]

In [30]:
from sklearn.preprocessing import LabelEncoder

In [31]:
label_encoder = LabelEncoder()

In [32]:
y_train = label_encoder.fit_transform(y_train)

In [33]:
y_train

array([1, 0, 0, ..., 0, 0, 0], dtype=int64)

In [34]:
print("y_train: \n\n {} \n" .format(y_train))
print("y_train.shape: {} \n" .format(y_train.shape))

y_train: 

 [1 0 0 ... 0 0 0] 

y_train.shape: (86845,) 



In [35]:
df.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [36]:
df_copy = df[(df["duration"] > 0) | (df["srcbytes"] > 0) | (df["dstbytes"])][["duration", "srcbytes", "dstbytes", "attack"]]

In [37]:
df_copy

duration  srcbytes  dstbytes  attack
1             0      1239       400       0
2             0       222       945       0
3             0       235      1380       0
5             0       348      2029       0
9             0       242       380       0
...         ...       ...       ...     ...
86840         0       216       674       0
86841         0       368      1725       0
86842        28      1483      4152       0
86843         0      1679       385       0
86844     11343      3396     16694       0

[51293 rows x 4 columns]

In [38]:
df_copy["attack"].unique()

array([0], dtype=int64)

In [39]:
df_copy["attack"].value_counts()

attack
0    51293
Name: count, dtype: int64

In [40]:
df_copy[df_copy["attack"] == "neptune"]

Empty DataFrame
Columns: [duration, srcbytes, dstbytes, attack]
Index: []

In [41]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [42]:
categorical_pipeline = Pipeline(steps = [

    ("imputer", SimpleImputer(strategy = "most_frequent")),
    ("encoder", OneHotEncoder())
])

numerical_pipeline = Pipeline(steps = [

    ("imputer", SimpleImputer(strategy = "median")),
    ("scaler", StandardScaler()),
])

In [43]:
preprocessor = ColumnTransformer(transformers = [

    ("numerical_pipeline", numerical_pipeline, numerical_features),
    ("categorical_pipeline", categorical_pipeline, non_encoded_category)
])

In [44]:
non_encoded_category

['protocoltype', 'service', 'flag']

In [45]:
df.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsamesrvrate  dsthostdiffsrvrate  \
0              0       0    0  ...                0.06                0.06   
1              0       0    0  ...                0.45                0.04   
2              0       0    0  ...                1.00                0.00   
3              0       0    0  ...                1.00                0.00   
4              0       0    0  ...                0.01                0.08   

   dsthostsamesrcportrate  dsthostsrvdiffhostrate  dsthostserrorrate  \
0                    0.00                    0.00               0.00   
1                    0.00                    0.00               0.11   
2                    0.02                    0.03               0.00   
3                    0.00                    0.00               0.00   
4                    0.00                    0.00               0.00   

   dsthostsrvserrorrate  dsthostrerrorrate  dsthostsrvrerrorrate  lastflag  \
0                   0.0               1.00                   1.0        21   
1                   0.0               0.02                   0.0        18   
2                   0.0               0.00                   0.0        21   
3                   0.0               0.00                   0.0        21   
4                   0.0               1.00                   1.0        19   

   attack  
0       1  
1       0  
2       0  
3       0  
4       1  

[5 rows x 43 columns]

In [46]:
x_train.head()

duration protocoltype      service flag  srcbytes  dstbytes  land  \
0         0          tcp  netbios_dgm  REJ         0         0     0   
1         0          tcp         smtp   SF      1239       400     0   
2         0          tcp         http   SF       222       945     0   
3         0          tcp         http   SF       235      1380     0   
4         0          tcp    uucp_path  REJ         0         0     0   

   wrongfragment  urgent  hot  ...  dsthostsrvcount  dsthostsamesrvrate  \
0              0       0    0  ...               15                0.06   
1              0       0    0  ...              116                0.45   
2              0       0    0  ...              255                1.00   
3              0       0    0  ...              255                1.00   
4              0       0    0  ...                3                0.01   

   dsthostdiffsrvrate  dsthostsamesrcportrate  dsthostsrvdiffhostrate  \
0                0.06                    0.00                    0.00   
1                0.04                    0.00                    0.00   
2                0.00                    0.02                    0.03   
3                0.00                    0.00                    0.00   
4                0.08                    0.00                    0.00   

   dsthostserrorrate  dsthostsrvserrorrate  dsthostrerrorrate  \
0               0.00                   0.0               1.00   
1               0.11                   0.0               0.02   
2               0.00                   0.0               0.00   
3               0.00                   0.0               0.00   
4               0.00                   0.0               1.00   

   dsthostsrvrerrorrate  lastflag  
0                   1.0        21  
1                   0.0        18  
2                   0.0        21  
3                   0.0        21  
4                   1.0        19  

[5 rows x 42 columns]

In [47]:
x_train_scaled = preprocessor.fit_transform(x_train).toarray()
x_test_scaled = preprocessor.transform(x_test).toarray()

In [48]:
x_train_scaled

array([[-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02014647, -0.04207272, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02298557, -0.03224051, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.07335958, -0.01946531,  0.02561614, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.01891815, -0.04234333, ...,  0.        ,
         1.        ,  0.        ],
       [10.82460202, -0.0141249 ,  0.25188313, ...,  0.        ,
         1.        ,  0.        ]])

In [49]:
x_test_scaled

array([[-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02304978, -0.0182409 , ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02352436, -0.04928902, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ]])

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
p_train, p_test, q_train, q_test = train_test_split(x_train_scaled, y_train, test_size = 0.20, random_state = 100)

In [52]:
p_train

array([[-0.10032758, -0.02243841,  0.06442178, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02216483, -0.04921685, ...,  0.        ,
         1.        ,  0.        ],
       ...,
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ]])

In [53]:
print("p_train: {}" .format(p_train))
print("p_train.shape: {}" .format(p_train.shape))

p_train: [[-0.10032758 -0.02243841  0.06442178 ...  0.          1.
   0.        ]
 [-0.10032758 -0.02360532 -0.04928902 ...  0.          0.
   0.        ]
 [-0.10032758 -0.02216483 -0.04921685 ...  0.          1.
   0.        ]
 ...
 [-0.10032758 -0.02360532 -0.04928902 ...  0.          0.
   0.        ]
 [-0.10032758 -0.02360532 -0.04928902 ...  0.          0.
   0.        ]
 [-0.10032758 -0.02360532 -0.04928902 ...  0.          0.
   0.        ]]
p_train.shape: (69476, 105)


In [54]:
p_test

array([[-0.10032758, -0.02352157, -0.04928902, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.01631354, -0.04331753, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02360532, -0.04928902, ...,  0.        ,
         0.        ,  0.        ],
       ...,
       [-0.10032758, -0.02290461, -0.00541393, ...,  0.        ,
         1.        ,  0.        ],
       [-0.10032758, -0.02295765,  0.05565398, ...,  0.        ,
         1.        ,  0.        ],
       [-0.09743815, -0.02052893, -0.04333557, ...,  0.        ,
         1.        ,  0.        ]])

In [55]:
print("p_test: {}" .format(p_test))
print("p_test.shape: {}" .format(p_test.shape))

p_test: [[-0.10032758 -0.02352157 -0.04928902 ...  0.          1.
   0.        ]
 [-0.10032758 -0.01631354 -0.04331753 ...  0.          1.
   0.        ]
 [-0.10032758 -0.02360532 -0.04928902 ...  0.          0.
   0.        ]
 ...
 [-0.10032758 -0.02290461 -0.00541393 ...  0.          1.
   0.        ]
 [-0.10032758 -0.02295765  0.05565398 ...  0.          1.
   0.        ]
 [-0.09743815 -0.02052893 -0.04333557 ...  0.          1.
   0.        ]]
p_test.shape: (17369, 105)


In [56]:
q_train

array([0, 0, 0, ..., 1, 1, 1], dtype=int64)

In [57]:
print("q_train: {}" .format(q_train))
print("q_train.shape: {}" .format(q_train.shape))

q_train: [0 0 0 ... 1 1 1]
q_train.shape: (69476,)


In [58]:
q_test

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [59]:
print("q_test: {}" .format(q_test))
print("q_test.shape: {}" .format(q_test.shape))

q_test: [0 0 1 ... 0 0 0]
q_test.shape: (17369,)


In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier, XGBRFClassifier
from xgboost import plot_tree, plot_importance
from sklearn.neighbors import KNeighborsClassifier

In [61]:
models = {

    "Logistic_Regression": LogisticRegression(),
    "Decision_Tree_Classifier": DecisionTreeClassifier(),
    "Support_Vector_Classifier": SVC(),
    "Gaussian_Naive_Bayes": GaussianNB(),
    "Random_Forest": RandomForestClassifier(),
    "AdaBoost_Classifier": AdaBoostClassifier(),
    "Gradient_Boost_Classifier": GradientBoostingClassifier(),
    "XGBoost_Classifier": XGBClassifier(),
    "XGBRF_Classifier": XGBRFClassifier(),
    "K_Neighbour_Classifier": KNeighborsClassifier(),  
}

In [62]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [63]:
def evaluate_model(p_train, p_test, q_train, q_test):
    report = {}
    for i in range(len(models)):
        model = list(models.values())[i]
        model.fit(p_train, q_train)
        q_pred = model.predict(p_test)
        accuracy = accuracy_score(q_test, q_pred)
        report[list(models.keys())[i]] = accuracy

    return report

In [64]:
evaluate_model(p_train, p_test, q_train, q_test)

{'Logistic_Regression': 0.999712130807761,
 'Decision_Tree_Classifier': 0.9997697046462087,
 'Support_Vector_Classifier': 0.9998848523231044,
 'Gaussian_Naive_Bayes': 0.9930911393862629,
 'Random_Forest': 1.0,
 'AdaBoost_Classifier': 0.9999424261615522,
 'Gradient_Boost_Classifier': 0.9999424261615522,
 'XGBoost_Classifier': 1.0,
 'XGBRF_Classifier': 0.999712130807761,
 'K_Neighbour_Classifier': 0.9998272784846566}

In [65]:
from sklearn.model_selection import GridSearchCV

In [66]:
parameters = {
    
    "max_depth": [3, 5, 10, None],
    "criterion": ["entropy", "gini"],
    "n_estimators": [100, 200, 300]
}

In [67]:
grid_search_cv = GridSearchCV(RandomForestClassifier(), param_grid = parameters, scoring = "accuracy", cv = 5, verbose = 3)

In [68]:
grid_search_cv.fit(p_train, q_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   3.6s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   3.6s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   3.5s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   3.3s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   3.4s
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   6.8s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   6.8s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   6.9s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   7.0s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total t

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['entropy', 'gini'],
                         'max_depth': [3, 5, 10, None],
                         'n_estimators': [100, 200, 300]},
             scoring='accuracy', verbose=3)

In [69]:
grid_search_cv.best_params_

{'criterion': 'entropy', 'max_depth': 10, 'n_estimators': 100}

In [70]:
grid_search_cv.best_score_

0.9999712147380542

In [71]:
q_pred = grid_search_cv.predict(p_test)

In [72]:
q_pred

array([0, 0, 1, ..., 0, 0, 0], dtype=int64)

In [73]:
print("Confusion_Matrix: \n\n {} \n" .format(confusion_matrix(q_test, q_pred)))
print("Accuracy: {} \n" .format(accuracy_score(q_test, q_pred)))
print("Classification Report: \n\n {} \n" .format(classification_report(q_test, q_pred)))

Confusion_Matrix: 

 [[10681     0]
 [    0  6688]] 

Accuracy: 1.0 

Classification Report: 

               precision    recall  f1-score   support

           0       1.00      1.00      1.00     10681
           1       1.00      1.00      1.00      6688

    accuracy                           1.00     17369
   macro avg       1.00      1.00      1.00     17369
weighted avg       1.00      1.00      1.00     17369
 



In [ ]:
grid_search_cv.fit(x_train_scaled, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   4.5s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   4.9s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   4.6s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   4.2s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=100;, score=1.000 total time=   4.4s
[CV 1/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   9.7s
[CV 2/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   9.8s
[CV 3/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total time=   9.4s
[CV 4/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=0.999 total time=  10.1s
[CV 5/5] END criterion=entropy, max_depth=3, n_estimators=200;, score=1.000 total t

In [ ]:
grid_search_cv.best_params_

In [ ]:
grid_search_cv.best_score_

In [ ]:
y_pred = grid_search_cv.predict(x_test_scaled)

In [ ]:
y_pred

In [ ]:
y_pred = pd.DataFrame(y_pred, columns = ["attack"])

In [ ]:
y_pred.head()

In [ ]:
for i in range(len(y_pred)):
    if y_pred["attack"][i] == 0:
        y_pred["attack"][i] = 1
    else:
        y_pred["attack"][i] = 0

In [ ]:
y_pred.head()

In [ ]:
y_pred.to_csv("Final_Submission.csv", index = False)